buildVariable: true
familyName: Noto Sans Gurmukhi
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
  - end: 700
    start: 700
recipeProvider: noto
sources:
- NotoSansGurmukhi.glyphs
