buildVariable: true
familyName: Noto Sans Gurmukhi
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
    - start: 0x02BC
      end: 0x2BC
sources:
- NotoSansGurmukhi.glyphs
