buildVariable: true
category:
- SERIF
familyName: Noto Serif Gurmukhi
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
- from: Noto Serif
  ranges:
  - end: 700
    start: 700
recipeProvider: noto
sources:
- NotoSerifGurmukhi.glyphs
